[package]
name = "mindrustry_arc"
version = "142.2.0"
edition = "2021"

[dependencies]
arc = { path = "./arc" }


[workspace]
members = [
    "arc",
    "mind",
    "mind/core",
    "mind/server",
    'mind/help_scripts'
]

[workspace.dependencies]
readonly = "0.2" # for making things read-only