[package]
name = "arc"
version = "142.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
once_cell = "1.17.1"
lazy_static = "1.4.0"
json = "0.12.4"
filepath = "0.1.2"
whoami = "1.3.0"
home = "0.5.4"
encoding_rs_io = "0.1"
num_cpus = "1.0"
